{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccm-hcloud-test.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ccm-hcloud-test.labels" . | nindent 4 }}
stringData:
  {{ .Values.secret.tokenKeyName }}: {{ .Values.env.hcloudApiToken | b64enc }}
{{- if .Values.privateNetwork.enabled }}
  {{ .Values.secret.networkKeyName }}: {{ .Values.privateNetwork.network.id | b64enc }}
{{- end -}}  
{{- end -}}
