{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ccm-hetzner-test.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ccm-hetzner-test.labels" . | nindent 4 }}
stringData:
  {{ .Values.secret.key.token }}: {{ .Values.env.hcloudApiToken | b64enc }}
  {{ .Values.secret.key.robotUserName }}: {{ .Values.env.robotUser | b64enc }}
  {{ .Values.secret.key.robotPassword }}: {{ .Values.env.robotPassword | b64enc }}
{{- if .Values.privateNetwork.enabled }}
  {{ .Values.secret.networkKeyName }}: {{ .Values.privateNetwork.network.id | b64enc }}
{{- end -}}  
{{- end -}}
